---

# This Ansible playbook destroys infrastructure in AWS that is part of a stack created with the given user name.

# To run this playbook:
# ansible-playbook -e "user_name=FOO" -i localhost, delete_infrastructure.yml

- hosts: all
  connection: local
  vars:
    - template_file: cloudformation-templates/infrastructure-complete.template
    - region: eu-west-1
  tasks:
  - name: Delete CloudFormation stack
    action: cloudformation stack_name="aws-workshop-{{ user_name }}" state=absent region={{ region }} disable_rollback=false template="{{ template_file }}"
